export const visualRoutes = [
  { path: '/', name: 'inicio' },
  { path: '/sobre-el-pueblo', name: 'sobre-el-pueblo' },
  { path: '/contacto', name: 'contacto' },
  { path: '/noticias', name: 'noticias' },
  { path: '/noticias/ayudas-despoblacion-cuenca', name: 'noticias-detalle' },
  { path: '/bandos', name: 'bandos' },
  {
    path: '/bandos/1386492-uso-de-las-fuentes-del-parque-y-fronton',
    name: 'bandos-detalle',
  },
  { path: '/aviso-legal', name: 'aviso-legal' },
  { path: '/galeria', name: 'galeria' },
  { path: '/galeria/album-1', name: 'album-1' },
  { path: '/galeria/album-2', name: 'album-2' },
  { path: '/testimonios', name: 'testimonios' },
  { path: '/buscar', name: 'buscar' },
  { path: '/politica-de-cookies', name: 'politica-de-cookies' },
  { path: '/politica-de-privacidad', name: 'politica-de-privacidad' },
];
