# GitHub backend configuration for Vercel deployment
backend:
  name: github
  repo: ralph1985/ayuntamiento-de-belmontejo
  branch: develop
  site_domain: develop-ayuntamiento-de-belmontejo.vercel.app
  base_url: https://develop-ayuntamiento-de-belmontejo.vercel.app
  auth_endpoint: oauth

# Enable editorial workflow for content approval process
publish_mode: editorial_workflow

local_backend: true

# Configurar idioma español
locale: 'es'

# Logo for Decap login page. Change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site link in DecapCMS (optional)
site_url: https://develop-ayuntamiento-de-belmontejo.vercel.app

media_folder: src/assets/images # Location where files will be stored in the repo - we store them in src so that Astro can optimize them.
public_folder: src/assets/images # Ensure that this path is the same as the media_folder path above.

# Quickly see who did what (optional)
commit_messages:
  create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
  update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
  delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
  uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}>
  deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}>
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}>

collections:
  - name: 'noticias' # Used in routes, e.g., /admin/collections/noticias. Is also the key when fetching data from the CMS.
    label: 'Noticias' # Used in the admin dashboard UI
    folder: 'src/content/noticias' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: 'src/assets/images/noticias' # Folder específico para imágenes de noticias
    public_folder: 'src/assets/images/noticias' # Ruta pública para imágenes de noticias
    fields: # The fields for each document
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Autor', name: 'author', widget: 'string' }
      - { label: 'Fecha', name: 'date', widget: 'datetime' }
      - { label: 'Imagen de portada', name: 'image', widget: 'image' }
      - {
          label: 'Descripción de la imagen',
          name: 'imageAlt',
          widget: 'string',
        }
      - {
          label: '¿Es una noticia destacada?',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }

  - name: 'bandos' # Used in routes, e.g., /admin/collections/bandos
    label: 'Bandos' # Used in the admin dashboard UI
    folder: 'src/content/bandos' # The path to the folder where the bandos are stored
    create: true # Allow users to create new bandos in this collection
    media_folder: 'src/assets/images/bandos' # Folder específico para imágenes de bandos
    public_folder: 'src/assets/images/bandos' # Ruta pública para imágenes de bandos
    fields: # The fields for each bando document
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - {
          label: 'Autor',
          name: 'author',
          widget: 'string',
          default: 'Ayuntamiento de Belmontejo',
        }
      - { label: 'Fecha', name: 'date', widget: 'datetime' }
      - {
          label: 'Imagen (opcional)',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Descripción de la imagen',
          name: 'imageAlt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Categoría',
          name: 'category',
          widget: 'string',
          default: 'Info General',
        }
      - {
          label: 'GUID',
          name: 'guid',
          widget: 'string',
          hint: 'Identificador único del bando (se genera automáticamente al sincronizar)',
        }
      - {
          label: 'Enlace original',
          name: 'link',
          widget: 'string',
          hint: 'URL del bando original en Bandomovil',
        }
      - {
          label: '¿Es un bando destacado?',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }

  - name: 'footer-services' # Collection for managing footer services links
    label: 'Enlaces de Servicios' # Used in the admin dashboard UI
    files:
      - label: 'Configuración de Enlaces de Servicios'
        name: 'services'
        file: 'src/data/footerServices.json'
        fields:
          - label: 'Enlaces de Servicios'
            name: 'services'
            widget: 'list'
            summary: '{{fields.title}} - {{fields.isActive}}'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', min: 1 }
              - { label: 'Título del enlace', name: 'title', widget: 'string' }
              - {
                  label: 'URL',
                  name: 'url',
                  widget: 'string',
                  required: false,
                  hint: 'Deja vacío si el enlace aún no tiene destino',
                }
              - {
                  label: '¿Es enlace externo?',
                  name: 'isExternal',
                  widget: 'boolean',
                  default: false,
                  hint: 'Marca esta opción si el enlace lleva a un sitio web externo',
                }
              - {
                  label: '¿Está activo?',
                  name: 'isActive',
                  widget: 'boolean',
                  default: false,
                  hint: 'Solo los enlaces activos aparecerán como enlaces clicables en el footer',
                }
