// This file gets generated by Astro automatically. It deals with types for TypeScript purposes.
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

interface ImportMetaEnv {
  readonly PUBLIC_APP_VERSION?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

interface Window {
  // eslint-disable-next-line no-unused-vars
  __applyMunicipalTheme?: (theme: 'light' | 'dark', persist?: boolean) => void;
}
